live:
- name: Ethereum
  networks:
  - chainid: 5
    explorer: https://goerli.etherscan.io/
    host: https://eth-goerli.g.alchemy.com/v2/QjUW7A_rEmw7pRMitKYbQsyhWCWFtIkr
    id: goerli-alchemy
    name: Goerli (alchemy)